models/Book.php
<?php

namespace app\models;

use Yii;
use yii\behaviors;
use yii\behaviors\SluggableBehavior;
// To use the Yii2 Query Builder for making SELECT queries
use yii\db\Query;
use yii\db\mssql\PDO;

/**
 * This is the model class for table "book".
 *
 * @property integer $idbook
 * @property string $title
 * @property string $description
 * @property string $date_entered
 * @property string $date_updated
 * @property integer $working
 * @property string $asin
 * @property string $isbn
 * @property string $isbn13
 * @property string $language
 * @property string $author
 * @property string $publisher
 * @property string $amazon_url
 * @property string $amazon_price_eur
 * @property string $amazon_cover_url
 */
class Book extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'book';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['description'], 'string'],
            [['date_entered', 'date_updated'], 'safe'],
            [['working'], 'integer'],
            [['amazon_cover_url'], 'required'],
            [['title'], 'string', 'max' => 100],
            [['asin', 'isbn', 'isbn13', 'language', 'author', 'publisher', 'amazon_price_eur'], 'string', 'max' => 45],
            [['amazon_url'], 'string', 'max' => 512],
            [['amazon_cover_url'], 'string', 'max' => 512],
            [['asin'], 'required'],
            [['asin'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'idbook' => 'Idbook',
            'title' => 'Título',
            'description' => 'Descripción',
            'date_entered' => 'Fecha de entrada',
            'date_updated' => 'Fecha de modificación',
            'working' => 'Activo',
            'asin' => 'Asin',
            'isbn' => 'Isbn',
            'isbn13' => 'Isbn13',
            'language' => 'Idioma',
            'author' => 'Autor',
            'publisher' => 'Editorial',
            'amazon_url' => 'Amazon - Url',
            'amazon_price_eur' => 'Amazon - Precio en €',
            'amazon_cover_url' => 'Amazon - URL a la portada',
        ];
    }

    public function behaviors() {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
            // 'slugAttribute' => 'slug',
            ],
        ];
    }


    
    /*
     * @action: favorite, pending, finished
     */
    public function userList($bookId, $userId, $action) {
        /* To prevent SQL injection attacks through DAO, you can either 
         * pass values in arrays, or use bound parameters 
         * Here I'm using bound parameters
         */
        $q = 'INSERT INTO user_book_'.$action.' (user_id, book_id, '.$action.') '
                . 'VALUES (:user_id, :book_id, 1) '
                . 'ON DUPLICATE KEY UPDATE '
                . $action.' = NOT '.$action;
        
        $cmd = Yii::$app->db->createCommand($q);
        $cmd->bindValue(':user_id', $userId, PDO::PARAM_INT);
        $cmd->bindValue(':book_id', $bookId, PDO::PARAM_INT);
        $cmd->execute();
    }

}

controllers/BookController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Book;
use app\models\BookSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
//use app\components\BaseController;
use yii\web\Response;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller {

    public $jsFile;

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete', 'favorites', 'pending', 'finished'],
                'rules' => [
                    [
                        'actions' => ['create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['moderador'], // Only the site administrators can do that
                    ],
                    [
                        'actions' => ['favorites', 'pending', 'finished'],
                        'allow' => true,
                        'roles' => ['@'], // All loged in users can favorite a book
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'ajax' => ['POST']
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new BookSearch([ 'working' => 1,]); // We will display only the working books
        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Book::find()
                    ->where(['working' => 1])
                    ->orderBy(['date_entered' => SORT_DESC])
            , 'pagination' => ['pageSize' => 12]
        ]);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Book models WITH A GRIDVIEW.
     * @return mixed
     */
    public function actionSearch() {
        $searchModel = new BookSearch([ 'working' => 1,]); // We will display only the working books
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=4;

        return $this->render('search', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /* -------- BOOK VIEW ROUTING --------
     * To avoid using the id in the book view route (as in /libro/1/el-club-de-la-lucha)
     * we need to:
     * 1. Change the route rule (found in /config/web.php) 
     *      to: 'libro/<id:\d+>/<slug>' => 'book/view',
     * 
     * 2. Disable the actionView($id) method
     * 3. Enable actionView($slug) and findModelBySlug($slug)
      
     * I choosed to use the ID in the route for SEO pourposes:
     * If the title is changed later on and we are using just the slug, the link  
     *      would become broken and we'd lose search engine traffic
     * Now the slug doesn't affect the routing, it just need to have any text
     *      F.e: /libro/1/a would work as well as /libro/1/el-club-de-la-lucha
     * 
     */
//    public function actionView($slug) {
//        return $this->render('view', [
//                    'model' => $this->findModelBySlug($slug),
//        ]);
//    }
//    protected function findModelBySlug($slug) {
//        if (($model = Post::findOne(['slug' => $slug])) !== null) {
//            return $model;
//        } else {
//            throw new NotFoundHttpException();
//        }
//    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Book();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $url = $model->amazon_cover_url;
            $img = \Yii::getAlias('@webroot').'/img/covers/'.$model->idbook.'.jpg';
            file_put_contents($img, file_get_contents($url));
            return $this->redirect(['view', 'id' => $model->idbook]);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }


    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $url = $model->amazon_cover_url;
            $img = \Yii::getAlias('@webroot').'/img/covers/'.$model->idbook.'.jpg';
            file_put_contents($img, file_get_contents($url));
            return $this->redirect(['view', 'id' => $model->idbook]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Book model.
     * But instead of deleting the row, we will set the working attribute to 0
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
//        $this->findModel($id)->delete(); // That method deletes the row
        $model = $this->findModel($id);
        $model->working = 0; // This way we are preserving the data
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {

        if (($model = Book::findOne($id)) !== null) {
            return $model;
//        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionFavorites() {

        $userId = Yii::$app->user->identity->id;

        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Book::find()
                    ->leftJoin('user_book_favorite', '`book`.`idbook` = `user_book_favorite`.`book_id`')
                    ->where(['user_book_favorite.user_id' => $userId,
                        'user_book_favorite.favorite' => 1,
                        'book.working' => 1])
                    ->orderBy(['user_book_favorite.timestamp_modified' => SORT_DESC])
            , 'pagination' => ['pageSize' => 12]
        ]);

        return $this->render('favorites', ['dataProvider' => $dataProvider,]);
    }

    public function actionPending() {
        $userId = Yii::$app->user->identity->id;

        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Book::find()
                    ->leftJoin('user_book_pending', '`book`.`idbook` = `user_book_pending`.`book_id`')
                    ->where(['user_book_pending.user_id' => $userId,
                        'user_book_pending.pending' => 1,
                        'book.working' => 1])
                    ->orderBy(['user_book_pending.timestamp_modified' => SORT_DESC])
            , 'pagination' => ['pageSize' => 12]
        ]);

        return $this->render('pending', ['dataProvider' => $dataProvider,]);
    }

    public function actionFinished() {
        $userId = Yii::$app->user->identity->id;

        $dataProvider = new ActiveDataProvider([
            'query' => \app\models\Book::find()
                    ->leftJoin('user_book_finished', '`book`.`idbook` = `user_book_finished`.`book_id`')
                    ->where(['user_book_finished.user_id' => $userId,
                        'user_book_finished.finished' => 1,
                        'book.working' => 1])
                    ->orderBy(['user_book_finished.timestamp_modified' => SORT_DESC])
            , 'pagination' => ['pageSize' => 12]
        ]);

        return $this->render('finished', ['dataProvider' => $dataProvider,]);
    }

    public function actionAjax() {
        if (Yii::$app->user->isGuest) {
            return error;
        }
        $userId = Yii::$app->user->identity->id;

        $bookId = Yii::$app->request->post('id');
        !$model = $this->findModel($bookId);
        if (!$model) {
            return error;
        }

        $ajaxAction = Yii::$app->request->post('action');
        switch ($ajaxAction) {
            case 'favorite':
            case 'pending':
            case 'finished':
                break;
            default:
                return error;
        }


        $model->userList($bookId, $userId, $ajaxAction);
    }
    

}

views/book/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?php
//    echo $form->field($model, 'date_entered')->textInput();
//    echo $form->field($model, 'date_updated')->textInput();
    ?>

    <?= $form->field($model, 'working')->textInput() ?>

    <?= $form->field($model, 'asin')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'isbn')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'isbn13')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'language')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'author')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'publisher')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'amazon_url')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'amazon_price_eur')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'amazon_cover_url')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/book/_list.php
<div class="row">
    <div class="col-sm-12">        

        <?php

        use yii\helpers\Html;
        use yii\helpers\Url;

foreach ($models as $model) {
            //    var_dump($model);
            ?>
            <div class="col-sm-4 col-md-3 col-lg-3 col-xs-6" >
                <div class = "well well-sm" >
                    <div class="item-image">
                        <a href = "
                        <?php
                        echo yii\helpers\Url::to(['/book/view', 'id' => $model['idbook'], 'slug' => $model->slug])
                        ?>">

                            <?php
                            echo Html::img(Url::to(Yii::getAlias('@web')."/img/covers/" . $model['idbook'] . ".jpg", true), ['class' => 'img-responsive',
                                'alt' => Html::encode($model->title),
                                'title' => Html::encode($model->title),
                                'style' => 'display: block; width: 100%']);
                            ?>
                    </div>
                    <div class="item-content hidden-xs visible-sm visible-md visible-lg">
                        <?php echo $model->title; ?>
                    </div>

                    </a>

                </div>
            </div>
            <?php
        }
        ?>
    </div>


</div>
<?php
echo \yii\widgets\LinkPager::widget([
    'pagination' => $dataProvider->pagination,
]);
?>

views/book/_menu.php
<?php

/*
 * This file is part of the Dektrium project
 *
 * (c) Dektrium project <http://github.com/dektrium>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

use yii\bootstrap\Nav;
?>

<?=

Nav::widget([
    'options' => [
        'class' => 'nav-tabs',
        'style' => 'margin-bottom: 15px',
//        'activateItems'=>'true',
//    'activateParents'=>'true',
    ],
    'items' => [
        [
            'label' => 'Novedades',
            'url' => ['/book/index'],
        ],
        [
            'label' => 'Buscar libro',
            'url' => ['/book/search'],
        ],
        [
            'label' => 'Mis favoritos',
            'url' => ['/book/favorites'],
        ],
        [
            'label' => 'Pendientes',
            'url' => ['/book/pending'],
        ],
        [
            'label' => 'Leídos',
            'url' => ['/book/finished'],
        ],
        [
            'visible' => (!Yii::$app->user->isGuest && Yii::$app->user->can('moderador')),
            'label' => 'Moderador',
            'items' => [
                [
                    'label' => 'Crear libro',
                    'url' => ['/book/create'],
                ],
            ],
        ],
        [
            'visible' => (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin),
            'label' => 'Administrador',
            'items' => [

                [

                    'label' => 'Ver',
                    'url' => ['/user/admin/'],
                    'items' => [
                        [
                            'label' => Yii::t('user', 'Users'),
                            'url' => ['/user/admin/index'],
                        ],
                        [
                            'label' => Yii::t('user', 'Roles'),
                            'url' => ['/rbac/role/index'],
                            'visible' => isset(Yii::$app->extensions['dektrium/yii2-rbac']),
                        ],
                        [
                            'label' => Yii::t('user', 'Permissions'),
                            'url' => ['/rbac/permission/index'],
                            'visible' => isset(Yii::$app->extensions['dektrium/yii2-rbac']),
                        ],
                    ],
                ],
                [

                    'label' => Yii::t('user', 'Create'),
                    'url' => ['/user/admin/'],
                    'items' => [
                        [
                            'label' => Yii::t('user', 'New user'),
                            'url' => ['/user/admin/create'],
                        ],
                        [
                            'label' => Yii::t('user', 'New role'),
                            'url' => ['/rbac/role/create'],
                            'visible' => isset(Yii::$app->extensions['dektrium/yii2-rbac']),
                        ],
                        [
                            'label' => Yii::t('user', 'New permission'),
                            'url' => ['/rbac/permission/create'],
                            'visible' => isset(Yii::$app->extensions['dektrium/yii2-rbac']),
                        ],
                    ],
                ],
            ],
        ],
    ],
])
?>

views/book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BookSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'idbook') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'date_entered') ?>

    <?= $form->field($model, 'date_updated') ?>

    <?php // echo $form->field($model, 'working') ?>

    <?php // echo $form->field($model, 'asin') ?>

    <?php // echo $form->field($model, 'isbn') ?>

    <?php // echo $form->field($model, 'isbn13') ?>

    <?php // echo $form->field($model, 'language') ?>

    <?php // echo $form->field($model, 'author') ?>

    <?php // echo $form->field($model, 'publisher') ?>

    <?php // echo $form->field($model, 'amazon_url') ?>

    <?php // echo $form->field($model, 'amazon_price_eur') ?>

    <?php // echo $form->field($model, 'amazon_cover_url') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/book/create.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;

/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = 'Crear libro';
$this->params['breadcrumbs'][] = ['label' => 'Libros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?=
Nav::widget([
    'options' => [
        'class' => 'nav-tabs',
        'style' => 'margin-bottom: 15px',
//        'activateItems'=>'true',
//    'activateParents'=>'true',
    ],
    'items' => [
        ['label' => 'Entrada manual', 'url' => ['/book/create']],
//        ['label' => 'Entrada automatica'], // Usando Api de amazon para auto rellenar
    ],
])
?>
<div class="book-create">

    <h1><?= Html::encode($this->title) ?></h1>

<?=
$this->render('_form', [
    'model' => $model,
])
?>

</div>

views/book/favorites.php
<?php

$this->title = 'Mis favoritos';
$this->params['breadcrumbs'][] = $this->title;
echo $this->render('/book/_menu');

$models = $dataProvider->getModels();

if (!$models) {
    echo 'No tienes ningún libro favorito todavía';
} else {
  
    echo $this->render('/book/_list', ['models' => $models, 'dataProvider' => $dataProvider]);
}
?>

views/book/finished.php
<?php

$this->title = 'Libros leídos';
$this->params['breadcrumbs'][] = $this->title;
echo $this->render('/book/_menu');

$models = $dataProvider->getModels();

if (!$models) {
    echo 'No has añadido ningún libro a tu lista de libros leídos';
} else {
  
    echo $this->render('/book/_list', ['models' => $models, 'dataProvider' => $dataProvider]);
}
?>

views/book/index.php
<?php

$this->title = 'Novedades';
$this->params['breadcrumbs'][] = $this->title;
echo $this->render('/book/_menu');

$models = $dataProvider->getModels();

if (!$models) {
    echo 'No hay libros en la base de datos';
} else {
  
    echo $this->render('/book/_list', ['models' => $models, 'dataProvider' => $dataProvider]);
}
?>

views/book/pending.php
<?php

$this->title = 'Libros pendientes';
$this->params['breadcrumbs'][] = $this->title;
echo $this->render('/book/_menu');

$models = $dataProvider->getModels();

if (!$models) {
    echo 'No tienes ningún libro pendiente todavía';
} else {
  
    echo $this->render('/book/_list', ['models' => $models, 'dataProvider' => $dataProvider]);
}
?>

views/book/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = 'Update Book: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->idbook]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/book/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use \dektrium\user\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Libros', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    .red{
        color: red;
    }
    .grey{
        color: grey;
    }
    .green{
        color: green;
    }
    .blue{
        color: blue;
    }
    .grey:hover {
        color: red;
    }
</style>

<script>
    function sendAjax(book_id, color, item) {
        var ajaxUrl = "<?php echo Yii::$app->getUrlManager()->createUrl('book/ajax'); ?>";
        var action = 'like';
        var title = '';

        switch (item.id) {
            case 'heart':
                action = 'favorite';
//                alert('corazon');
                break;
            case 'clock':
                action = 'pending';
//                alert('reloj');
                break;
            case 'eye':
                action = 'finished';
//                alert('ojo');
                break;
        }
        $.ajax({
            type: "POST",
            url: "<?php echo Yii::$app->getUrlManager()->createUrl('book/ajax'); ?>",
            data: {id: book_id, action: action},
            success: function () {

                if (item.id === 'heart') {
                    $('#heart').toggleClass('glyphicon-heart-empty glyphicon-heart');
                }
                $(item).toggleClass('grey ' + color);
            },
            error: function () {
                var r = confirm("Necesitas haber iniciado sesión");
                if (r == true) {
                    window.location.replace('<?php echo Yii::$app->getUrlManager()->createUrl('user/login'); ?>')
                }

            }
        })
    }

</script>
<?= $this->render('/book/_menu') ?>
<?php
$favorite_class = "grey glyphicon glyphicon-heart-empty";
$pending_class = "grey glyphicon glyphicon-time";
$finished_class = "grey glyphicon glyphicon-eye-open";

if (!Yii::$app->user->isGuest) {
    $userId = Yii::$app->user->identity->id;
    $favorite = User::inList($model->idbook, $userId, 'favorite');
    $pending = User::inList($model->idbook, $userId, 'pending');
    $finished = User::inList($model->idbook, $userId, 'finished');
    if ($favorite) {
        $favorite_class = "red glyphicon glyphicon-heart";
    }
    if ($pending) {
        $pending_class = "blue glyphicon glyphicon-time";
    }
    if ($finished) {
        $finished_class = "green glyphicon glyphicon-eye-open";
    }
}
?>
<div class="book-view">

    <h1>
        <span id='heart' title='Favorito' style="font-size: x-large" class="<?= $favorite_class ?>" 
              onclick="sendAjax(<?= $model->idbook ?>, 'red', this)" onhover='color=red'></span>
        <span id='clock' title='Pendiente' style="font-size: x-large" class="<?= $pending_class ?>" 
              onclick="sendAjax(<?= $model->idbook ?>, 'blue', this)"></span>
        <span id='eye' title='Leído' style="font-size: x-large" class="<?= $finished_class ?>" 
              onclick="sendAjax(<?= $model->idbook ?>, 'green', this)"></span>
              <?= Html::encode($this->title) ?>
    </h1>

    <p>

        <?php
        if (!Yii::$app->user->isGuest && Yii::$app->user->can('moderador')) {
            echo Html::a('Update', ['update', 'id' => $model->idbook], ['class' => 'btn btn-primary']);
            echo ' ';

            echo Html::a('Delete', ['delete', 'id' => $model->idbook], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]);

            echo DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'idbook',
                    'title',
                    'description:ntext',
                    'date_entered',
                    'date_updated',
                    'working',
                    'asin',
                    'isbn',
                    'isbn13',
                    'language',
                    'author',
                    'publisher',
                    'amazon_url:url',
                    'amazon_price_eur',
                    'amazon_cover_url:url',
                    ['label' => 'Comprar',
                        'format' => 'raw',
                        'value' => Html::a("Amazon ($model->amazon_price_eur €)", $model->amazon_url, ['class' => 'btn btn-warning', 'target' => '_blank'])],
                ],
            ]);
        } else {
            echo DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'title',
                    'author',
                    'description:ntext',
                    'publisher',
//                    'amazon_url:url',
//                    'amazon_price_eur',
                    ['label' => 'Comprar',
                        'format' => 'raw',
                        'value' => Html::a("Amazon ($model->amazon_price_eur €)", $model->amazon_url, ['class' => 'btn btn-warning', 'target' => '_blank'])],
                ],
            ]);
        }
        ?>
    </p>



</div>
<div id="disqus_thread"></div>
<script>
    /**
     * RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     * LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */

    var disqus_config = function () {
//     this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = '<?= $model->idbook ?>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//caralibro2016.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-57471715a5295955"></script>